# Generated by Django 3.1.7 on 2021-08-23 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.TextField(max_length=50)),
                ('codigo', models.TextField(max_length=20)),
                ('status', models.TextField(max_length=5)),
                ('descripcion', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidad', models.TextField(max_length=50)),
                ('documento', models.TextField(max_length=50, null=True)),
                ('cedula', models.TextField(max_length=20)),
                ('nombre', models.TextField(max_length=50)),
                ('apellido', models.TextField(max_length=50)),
                ('sexo', models.TextField(max_length=2)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.TextField(max_length=50, null=True)),
                ('telefono', models.TextField(max_length=50)),
                ('correo', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Examen_detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(max_length=20)),
                ('status', models.TextField(max_length=5)),
                ('descripcion', models.TextField(max_length=50)),
                ('resultado', models.TextField(max_length=50)),
                ('unidad', models.TextField(max_length=50)),
                ('valor_referencia', models.TextField(max_length=50)),
                ('id_examen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apicnc.examen')),
            ],
        ),
    ]
