# Generated by Django 3.1.7 on 2021-08-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicnc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nacionalidad',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
