# Generated by Django 3.1.7 on 2021-08-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicnc', '0002_auto_20210823_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name=('%d %b %Y', '%d %b, %Y')),
        ),
    ]
