# Generated by Django 3.1.7 on 2021-08-25 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apicnc', '0005_auto_20210825_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apicnc.paciente'),
        ),
    ]
