# Generated by Django 3.1.7 on 2021-08-26 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apicnc', '0007_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apicnc.factura'),
        ),
    ]
