# Generated by Django 3.1.7 on 2021-08-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicnc', '0008_examen_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='numero_factura',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
