# Generated by Django 3.1.7 on 2021-08-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicnc', '0009_factura_numero_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='correo',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
